language: python
sudo: required
dist: trusty
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  apt-get install pandoc
script:
  - pandoc --from markdown --to rst --output README.rst README.md
  - python manage.py test --noinput